/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["meta_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["workspaces_list_workspaces"];
        put?: never;
        /** Create Workspace */
        post: operations["workspaces_create_workspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["workspaces_get_workspace"];
        put?: never;
        post?: never;
        /** Delete Workspace */
        delete: operations["workspaces_delete_workspace"];
        options?: never;
        head?: never;
        /** Update Workspace */
        patch: operations["workspaces_update_workspace"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/ai-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ai Settings */
        get: operations["ai_get_ai_settings"];
        /** Put Ai Settings */
        put: operations["ai_put_ai_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["assets_list_assets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Asset */
        delete: operations["assets_delete_asset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/brand-docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Brand Docs */
        get: operations["brand_list_brand_docs"];
        put?: never;
        /** Upload Brand Doc */
        post: operations["brand_upload_brand_doc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/brand-docs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Retrieval */
        post: operations["brand_test_retrieval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/brand-docs/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Brand Url */
        post: operations["brand_import_brand_url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/brand-docs/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Brand Doc */
        delete: operations["brand_delete_brand_doc"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/brand-docs/{doc_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex Brand Doc */
        post: operations["brand_reindex_brand_doc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/brand-index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brand Index Status */
        get: operations["brand_brand_index_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/brand-index/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex Stale */
        post: operations["brand_reindex_stale"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/brand-kit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brand Kit */
        get: operations["workspaces_get_brand_kit"];
        /** Put Brand Kit */
        put: operations["workspaces_put_brand_kit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/brand-kit/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Brand Logo */
        post: operations["assets_upload_brand_logo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/brand-kit/voice-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voice From Samples */
        post: operations["brand_voice_from_samples"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Content */
        get: operations["content_list_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/content/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Content
         * @description Streams progress as SSE: `step`, `variant`, `item`, then `done` or `error`.
         */
        post: operations["content_generate_content"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/content/hashtags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hashtags */
        post: operations["content_hashtags"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/content/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content */
        get: operations["content_get_content"];
        put?: never;
        post?: never;
        /** Delete Content */
        delete: operations["content_delete_content"];
        options?: never;
        head?: never;
        /** Edit Content */
        patch: operations["content_edit_content"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/content/{item_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Variant */
        post: operations["content_regenerate_variant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage */
        get: operations["ai_usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AISettingsIn */
        AISettingsIn: {
            /** Daily Spend Cap Usd */
            daily_spend_cap_usd?: number | null;
            /** Routes */
            routes?: {
                [key: string]: components["schemas"]["PurposeRoute"];
            };
        };
        /** AISettingsOut */
        AISettingsOut: {
            /** Catalog */
            catalog: components["schemas"]["CatalogModel"][];
            /** Configured Providers */
            configured_providers: string[];
            /** Daily Spend Cap Usd */
            daily_spend_cap_usd: number | null;
            /** Default Daily Cap Usd */
            default_daily_cap_usd: number;
            /** Effective */
            effective: {
                [key: string]: components["schemas"]["EffectiveRoute"];
            };
            /** Routes */
            routes: {
                [key: string]: components["schemas"]["PurposeRoute"];
            };
        };
        /**
         * AssetKind
         * @enum {string}
         */
        AssetKind: "image" | "poster" | "logo" | "upload";
        /** AssetOut */
        AssetOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Height */
            height: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["AssetKind"];
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /** Mime Type */
            mime_type: string;
            /** Parent Id */
            parent_id: string | null;
            /** Size Bytes */
            size_bytes: number | null;
            source: components["schemas"]["AssetSource"];
            /** Url */
            url: string;
            /** Variant */
            variant: string | null;
            /** Width */
            width: number | null;
        };
        /**
         * AssetSource
         * @enum {string}
         */
        AssetSource: "generated" | "uploaded" | "rendered";
        /** Body_assets_upload_brand_logo */
        Body_assets_upload_brand_logo: {
            /** File */
            file: string;
        };
        /** Body_brand_upload_brand_doc */
        Body_brand_upload_brand_doc: {
            /** File */
            file: string;
        };
        /** BrandDocumentOut */
        BrandDocumentOut: {
            /** Chunk Count */
            chunk_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Embedding Model */
            embedding_model?: string | null;
            /** Error */
            error: string | null;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mime Type */
            mime_type: string;
            /**
             * Needs Reindex
             * @default false
             */
            needs_reindex: boolean;
            /** Size Bytes */
            size_bytes: number | null;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "file" | "url";
            /** Source Url */
            source_url: string | null;
            status: components["schemas"]["DocumentStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BrandKitIn */
        BrandKitIn: {
            /** Accent Colors */
            accent_colors?: string[];
            /** Body Font */
            body_font?: string | null;
            /** Do Words */
            do_words?: string[];
            /** Dont Words */
            dont_words?: string[];
            /** Heading Font */
            heading_font?: string | null;
            /** Logo Asset Id */
            logo_asset_id?: string | null;
            /** Primary Color */
            primary_color?: string | null;
            /** Sample Posts */
            sample_posts?: string[];
            /** Secondary Color */
            secondary_color?: string | null;
            voice_profile?: components["schemas"]["VoiceProfile"] | null;
            /** Voice Tone */
            voice_tone?: string | null;
        };
        /** BrandKitOut */
        BrandKitOut: {
            /** Accent Colors */
            accent_colors?: string[];
            /** Body Font */
            body_font?: string | null;
            /** Do Words */
            do_words?: string[];
            /** Dont Words */
            dont_words?: string[];
            /** Heading Font */
            heading_font?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Logo Asset Id */
            logo_asset_id?: string | null;
            /** Logo Palette */
            logo_palette?: components["schemas"]["PaletteColorOut"][];
            /** Logo Url */
            logo_url?: string | null;
            /** Primary Color */
            primary_color?: string | null;
            /** Sample Posts */
            sample_posts?: string[];
            /** Secondary Color */
            secondary_color?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            voice_profile?: components["schemas"]["VoiceProfile"] | null;
            /** Voice Tone */
            voice_tone?: string | null;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** BrandUrlIn */
        BrandUrlIn: {
            /**
             * Max Pages
             * @default 10
             */
            max_pages: number;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** CatalogModel */
        CatalogModel: {
            /** Embedding */
            embedding: boolean;
            /** Input Per M */
            input_per_m: number | null;
            /** Model */
            model: string;
            /** Output Per M */
            output_per_m: number | null;
            /** Price Official */
            price_official: boolean | null;
            /** Provider */
            provider: string;
            /** Structured */
            structured: string;
        };
        /**
         * Channel
         * @enum {string}
         */
        Channel: "instagram_post" | "instagram_carousel" | "linkedin_post" | "x_post" | "email" | "poster";
        /**
         * ContentEditIn
         * @description Inline edit: send the full structured content for the item's channel.
         */
        ContentEditIn: {
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /** Title */
            title?: string | null;
        };
        /** ContentItemOut */
        ContentItemOut: {
            /**
             * Blocked
             * @default false
             */
            blocked: boolean;
            /** Body */
            body: string;
            /** Campaign Id */
            campaign_id: string | null;
            channel: components["schemas"]["Channel"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Critique Score */
            critique_score: number | null;
            /** Generation */
            generation: {
                [key: string]: unknown;
            };
            /** Hashtags */
            hashtags: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            status: components["schemas"]["ContentStatus"];
            /** Title */
            title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Variant Group */
            variant_group: string | null;
            /** Variant Label */
            variant_label: string | null;
            /** Violations */
            violations?: components["schemas"]["ViolationOut"][];
        };
        /**
         * ContentStatus
         * @enum {string}
         */
        ContentStatus: "draft" | "in_review" | "approved" | "scheduled" | "published" | "failed";
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "pending" | "processing" | "ready" | "failed";
        /** EffectiveRoute */
        EffectiveRoute: {
            /** Error */
            error?: string | null;
            /** Model */
            model: string | null;
            /** Provider */
            provider: string | null;
            /** Source */
            source: string;
        };
        /** GenerateIn */
        GenerateIn: {
            /** Brief */
            brief: string;
            /** Campaign Id */
            campaign_id?: string | null;
            channel: components["schemas"]["Channel"];
            /**
             * Critique
             * @default true
             */
            critique: boolean;
            /**
             * N Variants
             * @default 3
             */
            n_variants: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HashtagsIn */
        HashtagsIn: {
            channel: components["schemas"]["Channel"];
            /** Text */
            text: string;
        };
        /** HashtagsOut */
        HashtagsOut: {
            /** Branded */
            branded: string[];
            /** Broad */
            broad: string[];
            /** Local */
            local: string[];
            /** Niche */
            niche: string[];
        };
        /** HealthOut */
        HealthOut: {
            /** Database */
            database: string;
            /** Status */
            status: string;
        };
        /** IndexStatusOut */
        IndexStatusOut: {
            /** Configured Dim */
            configured_dim: number;
            /** Configured Model */
            configured_model: string | null;
            /** Needs Reindex */
            needs_reindex: boolean;
            /** Stale Documents */
            stale_documents: number;
        };
        /**
         * Industry
         * @enum {string}
         */
        Industry: "fashion" | "food" | "tech" | "fitness" | "beauty" | "education" | "finance" | "real_estate" | "healthcare" | "travel" | "automotive" | "home" | "entertainment" | "pet" | "retail";
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LogoUploadOut */
        LogoUploadOut: {
            /** Has Existing Colors */
            has_existing_colors: boolean;
            logo: components["schemas"]["AssetOut"];
            /** Palette */
            palette: components["schemas"]["PaletteColorOut"][];
            thumbnail: components["schemas"]["AssetOut"];
        };
        /** MetaOut */
        MetaOut: {
            /** Channels */
            channels: components["schemas"]["Channel"][];
            /** Industries */
            industries: components["schemas"]["Industry"][];
        };
        /** PaletteColorOut */
        PaletteColorOut: {
            /**
             * Best Text
             * @enum {string}
             */
            best_text: "#FFFFFF" | "#000000";
            /** Contrast Black */
            contrast_black: number;
            /** Contrast White */
            contrast_white: number;
            /** Hex */
            hex: string;
            /**
             * Rating On Black
             * @enum {string}
             */
            rating_on_black: "AAA" | "AA" | "AA large" | "fail";
            /**
             * Rating On White
             * @enum {string}
             */
            rating_on_white: "AAA" | "AA" | "AA large" | "fail";
            /**
             * Role
             * @enum {string}
             */
            role: "primary" | "secondary" | "accent" | "extra";
            /** Share */
            share: number;
        };
        /**
         * Purpose
         * @description What a call is for. Workspaces can route each purpose to a different provider/model.
         * @enum {string}
         */
        Purpose: "writing" | "critique" | "planning" | "embedding";
        /** PurposeRoute */
        PurposeRoute: {
            /** Model */
            model: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "groq" | "gemini" | "openai" | "anthropic";
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
            /** Password */
            password: string;
        };
        /** RetrievalOut */
        RetrievalOut: {
            /** Chunks */
            chunks: components["schemas"]["RetrievedChunkOut"][];
            /** Dropped Below Threshold */
            dropped_below_threshold: number;
            /** Min Score */
            min_score: number;
            /** Query */
            query: string;
        };
        /** RetrievalQueryIn */
        RetrievalQueryIn: {
            /**
             * K
             * @default 6
             */
            k: number;
            /** Query */
            query: string;
        };
        /** RetrievedChunkOut */
        RetrievedChunkOut: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Content */
            content: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Heading */
            heading: string | null;
            /** Page */
            page: number | null;
            /** Score */
            score: number;
            /** Source */
            source: string;
        };
        /** SessionOut */
        SessionOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** UsageOut */
        UsageOut: {
            /** By Day */
            by_day: components["schemas"]["UsageRow"][];
            /** By Model */
            by_model: components["schemas"]["UsageRow"][];
            /** By Task */
            by_task: components["schemas"]["UsageRow"][];
            /** Daily Cap Usd */
            daily_cap_usd: number;
            /** Month */
            month: string;
            /** Timezone */
            timezone: string;
            /** Today Spent Usd */
            today_spent_usd: number;
            totals: components["schemas"]["UsageRow"];
        };
        /** UsageRow */
        UsageRow: {
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
            /** Errors */
            errors: number;
            /** Key */
            key: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Unknown Cost Calls */
            unknown_cost_calls: number;
        };
        /** UserOut */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ViolationOut */
        ViolationOut: {
            /**
             * Field
             * @default
             */
            field: string;
            /** Message */
            message: string;
            /** Rule */
            rule: string;
            /** Severity */
            severity: string;
        };
        /** VoiceFromSamplesIn */
        VoiceFromSamplesIn: {
            /** Samples */
            samples: string[];
        };
        /**
         * VoiceProfile
         * @description Structured brand voice, produced from sample posts by the LLM and editable by users.
         */
        VoiceProfile: {
            /** Do Words */
            do_words?: string[];
            /** Dont Words */
            dont_words?: string[];
            /**
             * Emoji Usage
             * @enum {string}
             */
            emoji_usage: "none" | "rare" | "moderate" | "frequent";
            /**
             * Formality
             * @description 1 = very casual, 5 = very formal
             */
            formality: number;
            /**
             * Sentence Length
             * @enum {string}
             */
            sentence_length: "short" | "medium" | "long" | "mixed";
            /** Signature Phrases */
            signature_phrases?: string[];
            /**
             * Summary
             * @description Two-sentence description of the voice.
             */
            summary: string;
            /** Tone Adjectives */
            tone_adjectives: string[];
        };
        /** WorkspaceCreate */
        WorkspaceCreate: {
            /** Audience */
            audience?: string | null;
            /** Description */
            description?: string | null;
            industry: components["schemas"]["Industry"];
            /** Locations */
            locations?: string[];
            /** Name */
            name: string;
            /**
             * Timezone
             * @default Asia/Kolkata
             */
            timezone: string;
            /** Website */
            website?: string | null;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /** Audience */
            audience: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            industry: components["schemas"]["Industry"];
            /** Locations */
            locations: string[];
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Website */
            website: string | null;
        };
        /** WorkspaceUpdate */
        WorkspaceUpdate: {
            /** Audience */
            audience?: string | null;
            /** Description */
            description?: string | null;
            industry?: components["schemas"]["Industry"] | null;
            /** Locations */
            locations?: string[] | null;
            /** Name */
            name?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Website */
            website?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    meta_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    workspaces_list_workspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"][];
                };
            };
        };
    };
    workspaces_create_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspaces_get_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspaces_delete_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspaces_update_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_get_ai_settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_put_ai_settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AISettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assets_list_assets: {
        parameters: {
            query?: {
                kind?: components["schemas"]["AssetKind"] | null;
                include_variants?: boolean;
                limit?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assets_delete_asset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_list_brand_docs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_upload_brand_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_brand_upload_brand_doc"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_test_retrieval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalQueryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_import_brand_url: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandUrlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_delete_brand_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_reindex_brand_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_brand_index_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_reindex_stale: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspaces_get_brand_kit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandKitOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspaces_put_brand_kit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandKitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandKitOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assets_upload_brand_logo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_assets_upload_brand_logo"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_voice_from_samples: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceFromSamplesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_list_content: {
        parameters: {
            query?: {
                status?: components["schemas"]["ContentStatus"][] | null;
                channel?: components["schemas"]["Channel"] | null;
                variant_group?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_generate_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateIn"];
            };
        };
        responses: {
            /** @description Server-sent events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_hashtags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HashtagsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HashtagsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_get_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_delete_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_edit_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentEditIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_regenerate_variant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_usage: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
